openapi: "3.0.2"
info:
  title: Cloud HIS Core
  version: "1.0"
  description: API Core for HIS platform

servers:
  - url: https://cloud-his-core-production.up.railway.app/

components:
  securitySchemes:
    bearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerToken: []

tags:
  - name: auth
    description: Operation about authentication
  - name: employee
    description: Operation about employee
  - name: entity
    description: Operation about authentication
  - name: organization
    description: Operation about organization
  - name: template
    description: Operation about template
  - name: zipcode
    description: Operation about zipcode

paths:
  /auth/send-reset-password:
    $ref: './Core/Auth/auth-send-reset-password.yaml'
  /employees:
    $ref: './Core/Employees/employees.yaml'
  /employee:
    $ref: './Core/Employees/employee.yaml'
  /employee/{id}:
    $ref: './Core/Employees/employee-id.yaml'
  /employee/find-by-email/{email}:
    $ref: './Core/Employees/employee-find-by-email-email.yaml'
  /employee/entity-of/{id}:
    $ref: './Core/Employees/employee-entity-of-id.yaml'
  /employee/assign-employee:
    $ref: './Core/Employees/employee-assign-employee.yaml'
  /employee/send-confirmation-email:
    $ref: './Core/Employees/employee-send-confirmation-email.yaml'
  /employee/change-status/{id}:
    $ref: './Core/Employees/employee-change-status-id.yaml'
  /employee/change-status-account/{id}:
    $ref: './Core/Employees/employee-change-status-account-id.yaml'
  /entities:
    $ref: './Core/Entities/entities.yaml'
  /entity:
    $ref: './Core/Entities/entity.yaml'
  /entities/find-by-employee/{id}:
    $ref: './Core/Entities/entities-find-by-employee-id.yaml'
  /entity/{id}:
    $ref: './Core/Entities/entity-id.yaml'
  /entity/change-status/{id}:
    $ref: './Core/Entities/entity-change-status-id.yaml'
  /entity/assign-employee:
    $ref: './Core/Entities/entity-assign-employee.yaml'
  /organizations:
    $ref: './Core/Organizations/organizations.yaml'
  /organization:
    $ref: './Core/Organizations/organization.yaml'
  /organization/{id}:
    $ref: './Core/Organizations/organization-id.yaml'
  /organization/send-activation-link:
    $ref: './Core/Organizations/organization-send-activation-link.yaml'
  /organization/activate/{account_email}:
    $ref: './Core/Organizations/organization-activate-account-email.yaml'
  /templates:
    $ref: "./Core/Template/templates.yaml"
  /template:
    $ref: "./Core/Template/template.yaml"
  /template/{id}:
    $ref: "./Core/Template/template-id.yaml"
  /zipcodes:
    $ref: './Core/Zipcodes/zipcodes.yaml'