openapi: "3.0.2"
info:
  title: Cloud HIS Frontdesk Module
  version: "1.0"
  description: Frontdesk API of Cloud HIS platform

servers:
  - url: https://somewhereonthecloud.com/v1

components:
  securitySchemes:
    bearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerToken: []

paths:
  /registration/{id}:
    get:
      description: Obtain information about an registration
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Successfully obtain information about an registration"
          content:
            application/json:
              schema:
                $ref: "./schemas/Entities.yaml"
