openapi: "3.0.2"
info:
  title: Cloud HIS Gateway
  version: "1.0"
  description: API Gateway for HIS platform

servers:
  - url: https://cloud-his-gateway-production.up.railway.app/

components:
  securitySchemes:
    bearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerToken: []

tags:
  - name: appointment
    description: Operation about appointment
  - name: auth
    description: Operation about authentication
  - name: dashboard
    description: Operation about dashboard
  - name: diagnose
    description: Operation about diagnose
  - name: employee
    description: Operation about employee
  - name: faskes
    description: Operation about faskes
  - name: guarantor
    description: Operation about guarantor
  - name: medical notes
    description: Operation about medical notes
  - name: organization
    description: Operation about organization
  - name: paramedic leave
    description: Operation about paramedic leave
  - name: paramedic schedule
    description: Operation about paramedic schedule
  - name: patient
    description: Operation about patient
  - name: registration
    description: Operation about registration
  - name: standard references
    description: Operation about standard references
  - name: template
    description: Operation about template
  - name: zipcode
    description: Operation about zipcode

paths:
  /appointments:
    $ref: "./Gateway/Appointment/appointments.yaml"
  /appointment:
    $ref: './Gateway/Appointment/appointment.yaml'
  /appointment/{id}:
    $ref: './Gateway/Appointment/appointment-id.yaml'
  /appointment/{id}/cancel:
    $ref: './Gateway/Appointment/appointment-id-cancel.yaml'
  /appointment/{id}/reschedule:
    $ref: './Gateway/Appointment/appointment-id-reschedule.yaml'
  /auth/check-role-faskes/{id}:
    $ref: './Gateway/Auth/auth-check-role-faskes.yaml'
  /auth/send-reset-password:
    $ref: './Gateway/Auth/auth-send-reset-password.yaml'
  /auth/reset-password:
    $ref: './Gateway/Auth/auth-reset-password.yaml'
  /auth/change-password:
    $ref: './Gateway/Auth/auth-change-password.yaml'
  /dashboard/employees/count:
    $ref: './Gateway/Dashboard/dashboard-employees-count.yaml'
  /dashboard/faskes/count:
    $ref: './Gateway/Dashboard/dashboard-faskes-count.yaml'
  /dashboard/patient/chart:
    $ref: './Gateway/Dashboard/dashboard-patient-chart.yaml'
  /dashboard/employees/chart:
    $ref: './Gateway/Dashboard/dashboard-employees-chart.yaml'
  /diagnoses:
    $ref: './Gateway/Diagnose/diagnoses.yaml'
  /employees:
    $ref: './Gateway/Employees/employees.yaml'
  /employee:
    $ref: './Gateway/Employees/employee.yaml'
  /employee/{id}:
    $ref: './Gateway/Employees/employee-id.yaml'
  /employee/faskes-of/{employee}:
    $ref: './Gateway/Employees/employee-faskes-of-employee.yaml'
  /employee/assign-to-faskes:
    $ref: './Gateway/Employees/employee-assign-employee.yaml'
  /employee/send-confirmation-link:
    $ref: './Gateway/Employees/employee-send-confirmation-email.yaml'
  /employee/change-status/{id}:
    $ref: './Gateway/Employees/employee-change-status-id.yaml'
  /employee/change-status-account/{id}:
    $ref: './Gateway/Employees/employee-change-status-account-id.yaml'
  /employee/create-account:
    $ref: './Gateway/Employees/employee-create-account.yaml'
  /employee/create-password:
    $ref: './Gateway/Employees/employee-create-password.yaml'
  /employee/rules/upload:
    $ref: './Gateway/Employees/employee-rules-upload.yaml'
  /employee/rules/latest:
    $ref: './Gateway/Employees/employee-rules-latest.yaml'
  /employee/rules/list:
    $ref: './Gateway/Employees/employee-rules-list.yaml'
  /employee/remove-faskes:
    $ref: './Gateway/Employees/employee-remove-faskes.yaml'
  /employee/cancel-invitation/{id}:
    $ref: './Gateway/Employees/employee-cancel-invitation-id.yaml'
  /faskes:
    $ref: './Gateway/Faskes/faskes.yaml'
  /faskes/employees/{id}:
    $ref: './Gateway/Faskes/faskes-find-by-employee-id.yaml'
  /faskes/{id}:
    $ref: './Gateway/Faskes/faskes-id.yaml'
  /faskes/change-status/{id}:
    $ref: './Gateway/Faskes/faskes-change-status-id.yaml'
  /faskes/upload-logo/{id}:
    $ref: './Gateway/Faskes/faskes-upload-logo-id.yaml'
  /faskes/upload-banner/{id}:
    $ref: './Gateway/Faskes/faskes-upload-logo-id.yaml'
  /faskes/assign:
    $ref: './Gateway/Faskes/faskes-assign-employee.yaml'
  /faskes/employee/remove:
    $ref: './Gateway/Faskes/faskes-remove-employee.yaml'
  /faskes/using_template:
    $ref: './Gateway/Faskes/faskes-using-template.yaml'
  /faskes/warehouse/{id}:
    $ref: './Gateway/Faskes/faskes-warehouse-id.yaml'
  /faskes/warehouse:
    $ref: './Gateway/Faskes/faskes-warehouse.yaml'
  /faskes/warehouse/share:
    $ref: './Gateway/Faskes/faskes-warehouse-share.yaml'
  /faskes/warehouse/void/{id}:
    $ref: './Gateway/Faskes/faskes-warehouse-void.yaml'
  /faskes/warehouse/depot/{id}:
    $ref: './Gateway/Faskes/faskes-warehouse-depot-id.yaml'
  /faskes/warehouse/depot:
    $ref: './Gateway/Faskes/faskes-warehouse-depot.yaml'
  /faskes/warehouse/depot/void/{id}:
    $ref: './Gateway/Faskes/faskes-warehouse-depot-void-id.yaml'
  /guarantors:
    $ref: './Gateway/Guarantor/guarantors.yaml'
  /guarantor/{id}:
    $ref: './Gateway/Guarantor/guarantor-id.yaml'
  /guarantor/detail/{id}:
    $ref: './Gateway/Guarantor/guarantor-detail-id.yaml'
  /guarantor:
    $ref: './Gateway/Guarantor/guarantor.yaml'
  /medical-notes:
    $ref: './Gateway/MedicalNotes/medical-notes.yaml'
  /medical-notes/mrn:
    $ref: './Gateway/MedicalNotes/medical-notes-mrn.yaml'
  /medical-notes/uid:
    $ref: './Gateway/MedicalNotes/medical-notes-uid.yaml'
  /medical-note:
    $ref: './Gateway/MedicalNotes/medical-note.yaml'
  /medical-note/{id}:
    $ref: './Gateway/MedicalNotes/medical-note-id.yaml'
  /medical-note/void/{id}:
    $ref: './Gateway/MedicalNotes/medical-note-void-id.yaml'
  /organizations:
    $ref: './Gateway/Organizations/organizations.yaml'
  /organization:
    $ref: './Gateway/Organizations/organization.yaml'
  /organization/{id}:
    $ref: './Gateway/Organizations/organization-id.yaml'
  /organization/send-activation-link:
    $ref: './Gateway/Organizations/organization-send-activation-link.yaml'
  /organization/activate/{account_email}:
    $ref: './Gateway/Organizations/organization-activate-account-email.yaml'
  /organization/{id}/settings:
    $ref: './Gateway/Organizations/organization-id-settings.yaml'
  /organization/{id}/settings/reset:
    $ref: './Gateway/Organizations/organization-id-settings-reset.yaml'
  /paramedic-leaves:
    $ref: './Gateway/ParamedicLeave/paramedic-leaves.yaml'
  /paramedic-leaves/{paramedic_id}/{service_unit_id}:
    $ref: './Gateway/ParamedicLeave/paramedic-leaves-paramedic-id-service-unit-id.yaml'
  /paramedic-leave:
    $ref: './Gateway/ParamedicLeave/paramedic-leave.yaml'
  /paramedic-leave/{id}:
    $ref: './Gateway/ParamedicLeave/paramedic-leave-id.yaml'
  /paramedic-schedules:
    $ref: './Gateway/ParamedicSchedule/paramedic-schedules.yaml'
  /paramedic-schedules/{paramedic_id}/{service_unit_id}:
    $ref: './Gateway/ParamedicSchedule/paramedic-schedules-paramedic-id-service-unit-id.yaml'
  /paramedic-schedule:
    $ref: './Gateway/ParamedicSchedule/paramedic-schedule.yaml'
  /patients:
    $ref: './Gateway/Patient/patients.yaml'
  /patient:
    $ref: './Gateway/Patient/patient.yaml'
  /patient/{id}:
    $ref: './Gateway/Patient/patient-id.yaml'
  /patient/mrn/{mrn}:
    $ref: './Gateway/Patient/patient-mrn.yaml'
  /patient/ssn/{ssn}:
    $ref: './Gateway/Patient/patient-ssn.yaml'
  /patient/blacklist/{id}:
    $ref: './Gateway/Patient/patient-blacklist-id.yaml'
  /patient/whitelist/{id}:
    $ref: './Gateway/Patient/patient-whitelist-id.yaml'
  /patient/decease/{id}:
    $ref: './Gateway/Patient/patient-decease-id.yaml'
  /patient/decease/delete/{id}:
    $ref: './Gateway/Patient/patient-decease-delete-id.yaml'
  /registrations:
    $ref: './Gateway/Registration/registrations.yaml'
  /registration:
    $ref: './Gateway/Registration/registration.yaml'
  /registration/{id}:
    $ref: './Gateway/Registration/registration-id.yaml'
  /registration/confirm-arrival:
    $ref: './Gateway/Registration/registration-confirm-arrival.yaml'
  /registration/start-service:
    $ref: './Gateway/Registration/registration-start-service.yaml'
  /registration/diagnose:
    $ref: './Gateway/Registration/registration-diagnose.yaml'
  /registration/medical-note:
    $ref: './Gateway/Registration/registration-medical-note.yaml'
  /registration/prescription:
    $ref: './Gateway/Registration/registration-prescription.yaml'
  /registration/end-service:
    $ref: './Gateway/Registration/registration-end-service.yaml'
  /registration/cancel:
    $ref: './Gateway/Registration/registration-cancel.yaml'
  /registration/discharge:
    $ref: './Gateway/Registration/registration-discharge.yaml'
  /registration/void:
    $ref: './Gateway/Registration/registration-void.yaml'
  /registration/{id}/guarantor/history:
    $ref: './Gateway/Registration/registration-id-guarantor-history.yaml'
  /registration/{id}/guarantor/change:
    $ref: './Gateway/Registration/registration-id-guarantor-change.yaml'
  /registration/{id}/cob/add:
    $ref: './Gateway/Registration/registration-id-cob-add.yaml'
  /registration/{id}/cob/remove:
    $ref: './Gateway/Registration/registration-id-cob-remove.yaml'
  /standard-reference/items/{group}:
    $ref: './Gateway/StandardReferences/standard-reference-items-group.yaml'
  /standard-reference/items/{id}:
    $ref: './Gateway/StandardReferences/standard-reference-items-create.yaml' 
  /standard-reference/item/{id}:
    $ref: './Gateway/StandardReferences/standard-reference-item-update.yaml'
  /templates/{category}:
    $ref: "./Gateway/Template/templates.yaml"
  /template:
    $ref: "./Gateway/Template/template-create.yaml"
  /template/{id}:
    $ref: "./Gateway/Template/template-id.yaml"
  /zipcodes:
    $ref: './Gateway/Zipcodes/zipcodes.yaml'