openapi: "3.0.2"
info:
  title: Cloud HIS Gateway
  version: "1.0"
  description: API Gateway for HIS platform

servers:
  - url: https://cloud-his-gateway-production.up.railway.app/

components:
  securitySchemes:
    bearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerToken: []

tags:
  - name: auth
    description: Operation about authentication
  - name: employee
    description: Operation about employee
  - name: entity
    description: Operation about entity
  - name: organization
    description: Operation about the organization
  - name: zipcode
    description: Operation about the zipcode

paths:
  /auth/check-role-entity/{id}:
    $ref: './Gateway/Auth/auth-check-role-entity.yaml'
  /auth/send-reset-password:
    $ref: './Gateway/Auth/auth-send-reset-password.yaml'
  /auth/reset-password:
    $ref: './Gateway/Auth/auth-reset-password.yaml'
  /employees:
    $ref: './Gateway/Employees/employees.yaml'
  /employee:
    $ref: './Gateway/Employees/employee.yaml'
  /employee/{id}:
    $ref: './Gateway/Employees/employee-id.yaml'
  /employee/assign-employee:
    $ref: './Gateway/Employees/employee-assign-employee.yaml'
  /employee/send-confirmation-email:
    $ref: './Gateway/Employees/employee-send-confirmation-email.yaml'
  /employee/change-status/{id}:
    $ref: './Gateway/Employees/employee-change-status-id.yaml'
  /employee/change-status-account/{id}:
    $ref: './Gateway/Employees/employee-change-status-account-id.yaml'
  /employee/create-account:
    $ref: './Gateway/Employees/employee-create-account.yaml'
  /employee/create-password:
    $ref: './Gateway/Employees/employee-create-password.yaml'
  /entities:
    $ref: './Gateway/Entities/entities.yaml'
  /entities/find-by-employee/{id}:
    $ref: './Gateway/Entities/entities-find-by-employee-id.yaml'
  /entity:
    $ref: './Gateway/Entities/entity.yaml'
  /entity/{id}:
    $ref: './Gateway/Entities/entity-id.yaml'
  /entity/change-status/{id}:
    $ref: './Gateway/Entities/entity-change-status-id.yaml'
  /entity/upload-logo/{id}:
    $ref: './Gateway/Entities/entity-upload-logo-id.yaml'
  /entity/upload-banner/{id}:
    $ref: './Gateway/Entities/entity-upload-logo-id.yaml'
  /organizations:
    $ref: './Gateway/Organizations/organizations.yaml'
  /organization:
    $ref: './Gateway/Organizations/organization.yaml'
  /organization/{id}:
    $ref: './Gateway/Organizations/organization-id.yaml'
  /organization/send-activation-link:
    $ref: './Gateway/Organizations/organization-send-activation-link.yaml'
  /organization/activate/{account_email}:
    $ref: './Gateway/Organizations/organization-activate-account-email.yaml'
  /zipcodes:
    $ref: './Gateway/Zipcodes/zipcodes.yaml'