openapi: "3.0.2"
info:
  title: Cloud-HIS Core
  version: "1.0"
  description: API Core for HIS platform
servers:
  - url: https://cloud-his-gateway-production.up.railway.app/
# components:
#   securitySchemes:
#     bearerToken:
#       type: http
#       scheme: bearer
#       bearerFormat: JWT
# security:
#   - bearerToken: []
tags:
  - name: auth
    description: Operation about authentication
paths:
  /auth/check-role-entity:
    get:
      tags:
        - auth
      description: Checking for roles and entity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                _id:
                  type: string
      responses:
        "200":
          description: Succesfully get all organization
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  message: 
                    type: string
        "401":
          $ref: "../responses/401.yaml"
        "403":
          $ref: "../responses/403.yaml"
        "500":
          $ref: "../responses/500.yaml"