openapi: "3.0.2"
info:
  title: Cloud HIS Gateway
  version: "1.0"
  description: API Gateway for HIS platform

servers:
  - url: https://cloud-his-gateway-production.up.railway.app/

components:
  securitySchemes:
    bearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerToken: []

tags:
  - name: class

paths:
  /classes:
    $ref: '../../Gateway/Class/classes.yaml'
  /class:
    $ref: '../../Gateway/Class/class.yaml'
  /class/{id}:
    $ref: '../../Gateway/Class/class-id.yaml'