openapi: "3.0.2"
info:
  title: Cloud-HIS Core
  version: "1.0"
  description: API Core for HIS platform
servers:
  - url: https://cloud-his-core.online
tags:
  - name: auth
    description: Authenticate user
paths:
  /auth/register:
    post:
      tags:
        - auth
      description: Register an organization and it owner
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../sub-schemas/AccountPost.yaml"
      responses:
        "201":
          description: Succesfully register an organization
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          $ref: "../responses/400.yaml"
        "401":
          $ref: "../responses/401.yaml"
  