openapi: "3.0.2"
info:
  title: Cloud HIS Gateway
  version: "1.0"
  description: API Gateway for HIS platform

servers:
  - url: https://cloud-his-gateway-production.up.railway.app/

components:
  securitySchemes:
    bearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerToken: []

tags:
  - name: template

paths:
  /templates/{category}:
    $ref: "../../Gateway/Template/templates.yaml"
  /template:
    $ref: "../../Gateway/Template/template-create.yaml"
  /template/{id}:
    $ref: "../../Gateway/Template/template-id.yaml"