openapi: "3.0.2"
info:
  title: Cloud HIS Gateway
  version: "1.0"
  description: API Gateway for HIS platform

servers:
  - url: https://cloud-his-gateway-production.up.railway.app/

components:
  securitySchemes:
    bearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerToken: []

tags:
  - name: auth

paths:
  /auth/check-role-faskes/{id}:
    $ref: '../../Gateway/Auth/auth-check-role-faskes.yaml'
  /auth/send-reset-password:
    $ref: '../../Gateway/Auth/auth-send-reset-password.yaml'
  /auth/reset-password:
    $ref: '../../Gateway/Auth/auth-reset-password.yaml'
  /auth/change-password:
    $ref: '../../Gateway/Auth/auth-change-password.yaml'