openapi: "3.0.2"
info:
  title: Cloud HIS Gateway
  version: "1.0"
  description: API Gateway for HIS platform

servers:
  - url: https://cloud-his-gateway-production.up.railway.app/

components:
  securitySchemes:
    bearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerToken: []

tags:
  - name: faskes

paths:
  /faskes:
    $ref: '../../Gateway/Faskes/faskes.yaml'
  /faskes/employees/{id}:
    $ref: '../../Gateway/Faskes/faskes-find-by-employee-id.yaml'
  /faskes/{id}:
    $ref: '../../Gateway/Faskes/faskes-id.yaml'
  /faskes/change-status/{id}:
    $ref: '../../Gateway/Faskes/faskes-change-status-id.yaml'
  /faskes/upload-logo/{id}:
    $ref: '../../Gateway/Faskes/faskes-upload-logo-id.yaml'
  /faskes/upload-banner/{id}:
    $ref: '../../Gateway/Faskes/faskes-upload-logo-id.yaml'
  /faskes/assign:
    $ref: '../../Gateway/Faskes/faskes-assign-employee.yaml'
  /faskes/employee/remove:
    $ref: '../../Gateway/Faskes/faskes-remove-employee.yaml'
  /faskes/using_template:
    $ref: '../../Gateway/Faskes/faskes-using-template.yaml'
  /faskes/warehouse/{id}:
    $ref: '../../Gateway/Faskes/faskes-warehouse-id.yaml'
  /faskes/warehouse:
    $ref: '../../Gateway/Faskes/faskes-warehouse.yaml'
  /faskes/warehouse/share:
    $ref: '../../Gateway/Faskes/faskes-warehouse-share.yaml'
  /faskes/warehouse/void/{id}:
    $ref: '../../Gateway/Faskes/faskes-warehouse-void.yaml'
  /faskes/warehouse/depot/{id}:
    $ref: '../../Gateway/Faskes/faskes-warehouse-depot-id.yaml'
  /faskes/warehouse/depot:
    $ref: '../../Gateway/Faskes/faskes-warehouse-depot.yaml'
  /faskes/warehouse/depot/void/{id}:
    $ref: '../../Gateway/Faskes/faskes-warehouse-depot-void-id.yaml'