openapi: "3.0.2"
info:
  title: Cloud HIS Gateway
  version: "1.0"
  description: API Gateway for HIS platform

servers:
  - url: https://cloud-his-gateway-production.up.railway.app/

components:
  securitySchemes:
    bearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerToken: []

tags:
  - name: paramedic leave

paths:
  /paramedic-leaves:
    $ref: '../../Gateway/ParamedicLeave/paramedic-leaves.yaml'
  /paramedic-leaves/{paramedic_id}/{service_unit_id}:
    $ref: '../../Gateway/ParamedicLeave/paramedic-leaves-paramedic-id-service-unit-id.yaml'
  /paramedic-leave:
    $ref: '../../Gateway/ParamedicLeave/paramedic-leave.yaml'
  /paramedic-leave/{id}:
    $ref: '../../Gateway/ParamedicLeave/paramedic-leave-id.yaml'