openapi: "3.0.2"
info:
  title: Cloud HIS Gateway
  version: "1.0"
  description: API Gateway for HIS platform

servers:
  - url: https://cloud-his-gateway-production.up.railway.app/

components:
  securitySchemes:
    bearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerToken: []

tags:
  - name: patient

paths:
  /patients:
    $ref: '../../Gateway/Patient/patients.yaml'
  /patient:
    $ref: '../../Gateway/Patient/patient.yaml'
  /patient/{id}:
    $ref: '../../Gateway/Patient/patient-id.yaml'
  /patient/mrn/{mrn}:
    $ref: '../../Gateway/Patient/patient-mrn.yaml'
  /patient/ssn/{ssn}:
    $ref: '../../Gateway/Patient/patient-ssn.yaml'
  /patient/blacklist/{id}:
    $ref: '../../Gateway/Patient/patient-blacklist-id.yaml'
  /patient/whitelist/{id}:
    $ref: '../../Gateway/Patient/patient-whitelist-id.yaml'
  /patient/decease/{id}:
    $ref: '../../Gateway/Patient/patient-decease-id.yaml'
  /patient/decease/delete/{id}:
    $ref: '../../Gateway/Patient/patient-decease-delete-id.yaml'
  /patient/allergic/{id}:
    $ref: '../../Gateway/Patient/patient-allergic-id.yaml'