get:
  tags:
    - organization
  description: Get an app settings for organization
  parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
  responses:
    "200":
      description: Succesfully get an app settings for organization
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: number
              message:
                type: string
              data:
                $ref: "../../schemas/AppSettings.yaml"
    "401":
      $ref: "../../responses/401.yaml"
    "403":
      $ref: "../../responses/403.yaml"
    "500":
      $ref: "../../responses/500.yaml"
put:
  tags:
    - organization
  description: Update an app settings for organization
  parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            account:
              type: object
              properties:
                invitationDuration: 
                  type: number
            branding:
              type: object
              properties:
                color: 
                  type: string
                logo: 
                  type: string
            rules:
              type: object
              properties:
                defaultView: 
                  type: string
  responses:
    "200":
      $ref: "../../responses/200.yaml"
    "401":
      $ref: "../../responses/401.yaml"
    "403":
      $ref: "../../responses/403.yaml"
    "500":
      $ref: "../../responses/500.yaml"